import { useState } from "react";
import { Card, CardBody, Input, Button, Select, SelectItem } from "@heroui/react";
import { toast } from "sonner";
import Switch from "./ui/Switch";
import { SparklesIcon } from "@heroicons/react/24/outline";
import { useSetting } from "../hooks/useSettings";
import { settingsService } from "../services/settingsService";
import { testAskAiConnection } from "../services/aiService";

const PROVIDERS = [
  { key: "openai", label: "OpenAI / OpenAI-compatible", model: "gpt-4o-mini" },
  { key: "anthropic", label: "Anthropic Claude", model: "claude-sonnet-4-5" },
  { key: "google", label: "Google Gemini", model: "gemini-2.0-flash" },
] as const;

export default function AiPanel() {
  const { value: aiEnabled, update: updateAiEnabled } = useSetting({
    key: "ai.enabled",
    fallbackValue: false,
  });
  const { value: provider, update: updateProvider } = useSetting({
    key: "ai.provider",
    fallbackValue: "openai",
  });
  const { value: model, update: updateModel } = useSetting({
    key: "ai.model",
    fallbackValue: "",
  });
  const { value: baseUrl, update: updateBaseUrl } = useSetting({
    key: "ai.baseUrl",
    fallbackValue: "",
  });
  const { value: apiKey, update: updateApiKey } = useSetting({
    key: "ai.apiKey",
    fallbackValue: "",
  });
  const { value: maxOutputTokens, update: updateMaxOutputTokens } = useSetting({
    key: "ai.maxOutputTokens",
    fallbackValue: 1024,
  });

  const inputClassNames = {
    inputWrapper:
      "border-[var(--docmate-border-color)] hover:border-[var(--docmate-text-secondary)] focus-within:border-[var(--docmate-primary)]! bg-[var(--docmate-surface-alt)]",
    input: "text-[var(--docmate-text)] placeholder:text-[var(--docmate-text-secondary)]/50",
  };

  const activeProvider =
    PROVIDERS.find((p) => p.key === (provider ?? "openai")) ?? PROVIDERS[0];

  const [isTesting, setIsTesting] = useState(false);

  const handleSave = async () => {
    const settings: Record<string, unknown> = {
      "ai.enabled": aiEnabled,
      "ai.provider": provider ?? "openai",
      "ai.model": model ?? "",
      "ai.baseUrl": baseUrl ?? "",
      "ai.apiKey": apiKey ?? "",
      "ai.maxOutputTokens":
        typeof maxOutputTokens === "number" && maxOutputTokens > 0 ? maxOutputTokens : 1024,
    };
    const result = await settingsService.updateSettings(settings);
    return result.success;
  };

  // Saves the current form values first, so the test always validates what
  // is on screen.
  const handleTestConnection = async () => {
    setIsTesting(true);
    try {
      if (!(await handleSave())) {
        toast.error("Could not save the AI settings");
        return;
      }
      const result = await testAskAiConnection();
      if (!result.ok) {
        toast.error(`Connection failed: ${result.error ?? "unknown error"}`);
        return;
      }
      if (!result.modelFound) {
        const available = (result.availableModels ?? []).slice(0, 8).join(", ");
        toast.warning(
          `Server reachable at ${result.baseUrl}, but the model "${result.model}" was not found there.` +
            (available ? ` Available models: ${available}` : "")
        );
        return;
      }
      toast.success(`Connected — ${result.model} is available at ${result.baseUrl}`);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : "The connection test failed");
    } finally {
      setIsTesting(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card className="bg-[var(--docmate-surface)] border-[var(--docmate-border-color)] border shadow-sm">
        <CardBody className="space-y-4 p-6">
          <div className="flex items-center gap-2 mb-4">
            <SparklesIcon className="w-5 h-5" style={{ color: "var(--docmate-primary)" }} />
            <h3 className="text-lg font-semibold">AI Assistant (Ask AI)</h3>
          </div>

          <Switch isSelected={aiEnabled} onValueChange={updateAiEnabled}>
            Enable the Ask AI assistant
          </Switch>
          <p className="text-sm mt-1" style={{ color: "var(--docmate-text-secondary)" }}>
            Shows an "Ask AI" button on documentation pages so readers can ask questions about the
            content. Answers are generated by the provider configured below; the API key never
            leaves the server.
          </p>

          <Select
            label="Provider"
            selectedKeys={[activeProvider.key]}
            onSelectionChange={(keys) => {
              const selected = Array.from(keys)[0];
              if (typeof selected === "string") updateProvider(selected);
            }}
            variant="bordered"
            isDisabled={!aiEnabled}
          >
            {PROVIDERS.map((p) => (
              <SelectItem key={p.key}>{p.label}</SelectItem>
            ))}
          </Select>

          <Input
            label="Model"
            placeholder={activeProvider.model}
            value={model ?? ""}
            onValueChange={updateModel}
            variant="bordered"
            isDisabled={!aiEnabled}
            description={`Leave empty to use the ${activeProvider.label} default (${activeProvider.model})`}
            classNames={inputClassNames}
          />

          {activeProvider.key === "openai" && (
            <Input
              label="API Base URL"
              placeholder="http://localhost:11434"
              value={baseUrl ?? ""}
              onValueChange={updateBaseUrl}
              variant="bordered"
              isDisabled={!aiEnabled}
              description="Server URL of any OpenAI-compatible endpoint (Ollama, LM Studio, vLLM, OpenRouter, …). The /v1 API path is added automatically when missing; leave empty for OpenAI."
              classNames={inputClassNames}
            />
          )}

          <Input
            label="API Key"
            type="password"
            placeholder="••••••••"
            value={apiKey ?? ""}
            onValueChange={updateApiKey}
            variant="bordered"
            isDisabled={!aiEnabled}
            description="Required for hosted providers; leave empty for keyless endpoints like Ollama. Can also be set via the AI_API_KEY environment variable, which takes precedence"
            classNames={inputClassNames}
          />

          <Input
            label="Max output tokens"
            type="number"
            placeholder="1024"
            value={String(maxOutputTokens ?? 1024)}
            onValueChange={(value) => {
              const parsed = Number(value);
              updateMaxOutputTokens(Number.isFinite(parsed) && parsed > 0 ? parsed : 1024);
            }}
            variant="bordered"
            isDisabled={!aiEnabled}
            description="Upper bound on the length of each AI answer"
            classNames={inputClassNames}
          />
        </CardBody>
      </Card>

      {/* Save Button */}
      <div className="flex justify-end gap-3 pt-4">
        <Button
          variant="flat"
          onPress={handleTestConnection}
          isDisabled={!aiEnabled || isTesting}
          className="bg-[var(--docmate-surface-alt)] text-[var(--docmate-text)] shadow-sm hover:shadow-md transition-shadow"
        >
          {isTesting ? "Testing…" : "Test connection"}
        </Button>
        <Button
          color="primary"
          onPress={handleSave}
          className="shadow-lg hover:shadow-xl transition-all duration-200 hover:-translate-y-0.5 px-8"
        >
          Save AI Settings
        </Button>
      </div>
    </div>
  );
}
