import { useState, useEffect, useCallback, type JSX } from 'react';
import { Card, CardBody, Chip, Button, Input, Tabs, Tab, Divider } from '@heroui/react';
import EnhancedCodeEditor from './enhancedCodeEditor';
import type { OpenApiSpec, OpenApiOperation, JsonSchema } from '../../types/docs';
import { performApiTest } from '../../utils/proxyRequest';

interface EmbeddedOperationViewerProps {
  operationId: string; // OpenAPI operation ID like "GET_root" or "get-/"
  spec: OpenApiSpec;
  baseUrl?: string;
}

interface TestRequest {
  pathParams?: Record<string, string>;
  queryParams?: Record<string, string>;
  headers?: Record<string, string>;
  body?: string;
}

interface TestResponse {
  status?: number;
  statusText?: string;
  headers?: Record<string, string>;
  data?: unknown;
  error?: string;
  url?: string;
}

const EmbeddedOperationViewer = ({ operationId, spec, baseUrl }: EmbeddedOperationViewerProps) => {
  const [operation, setOperation] = useState<OpenApiOperation | null>(null);
  const [path, setPath] = useState<string>('');
  const [method, setMethod] = useState<string>('');
  const [testRequest, setTestRequest] = useState<TestRequest>({});
  const [testResponse, setTestResponse] = useState<TestResponse | null>(null);
  const [isTestLoading, setIsTestLoading] = useState(false);

  const findOperation = useCallback(() => {
    if (!spec?.paths) return;

    // Try to find by operationId first (e.g., "GET_root")
    for (const [pathKey, pathItem] of Object.entries(spec.paths)) {
      for (const [methodKey, op] of Object.entries(pathItem)) {
        if (!['get', 'post', 'put', 'patch', 'delete', 'head', 'options'].includes(methodKey.toLowerCase())) continue;

        // Match by operationId
        if (op.operationId === operationId) {
          setOperation(op);
          setPath(pathKey);
          setMethod(methodKey.toUpperCase());
          return;
        }

        // Match by method-path format (e.g., "get-/")
        const compositeId = `${methodKey.toLowerCase()}-${pathKey}`;
        if (compositeId === operationId.toLowerCase()) {
          setOperation(op);
          setPath(pathKey);
          setMethod(methodKey.toUpperCase());
          return;
        }

        // Match by "METHOD path" format (e.g., "GET /")
        const methodPathId = `${methodKey.toUpperCase()} ${pathKey}`;
        if (methodPathId === operationId) {
          setOperation(op);
          setPath(pathKey);
          setMethod(methodKey.toUpperCase());
          return;
        }

        // Match by auto-generated ID format that might be in the spec
        const cleanPath = pathKey.replace(/^\//, '').replace(/\//g, '_') || 'root';
        const autoGeneratedId = `${methodKey.toUpperCase()}_${cleanPath}`;
        if (autoGeneratedId === operationId) {
          setOperation(op);
          setPath(pathKey);
          setMethod(methodKey.toUpperCase());
          return;
        }
      }
    }

    console.warn(`Operation not found: ${operationId}`);
    console.log('Available operations in spec:', Object.entries(spec.paths).flatMap(([path, pathItem]) =>
      Object.entries(pathItem)
        .filter(([method]) => ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'].includes(method.toLowerCase()))
        .map(([method, op]) => ({
          path,
          method: method.toUpperCase(),
          operationId: op.operationId,
          autoId: `${method.toUpperCase()}_${path.replace(/^\//, '').replace(/\//g, '_') || 'root'}`,
          compositeId: `${method.toLowerCase()}-${path}`
        }))
    ));
  }, [operationId, spec]);

  useEffect(() => {
    findOperation();
  }, [findOperation]);

  const getMethodColor = (method: string) => {
    switch (method.toUpperCase()) {
      case 'GET':
        return 'success';
      case 'POST':
        return 'primary';
      case 'PUT':
        return 'warning';
      case 'PATCH':
        return 'secondary';
      case 'DELETE':
        return 'danger';
      default:
        return 'default';
    }
  };

  const renderParametersTable = (parameters: OpenApiOperation['parameters']) => {
    if (!parameters || parameters.length === 0) return null;

    return (
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)]">
            <tr>
              <th className="px-4 py-2 text-left font-semibold">Name</th>
              <th className="px-4 py-2 text-left font-semibold">Type</th>
              <th className="px-4 py-2 text-left font-semibold">In</th>
              <th className="px-4 py-2 text-left font-semibold">Description</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
            {parameters.map((param, index) => (
              <tr key={index}>
                <td className="px-4 py-2">
                  <code className="text-sm font-mono">{param.name}</code>
                  {param.required && <span className="text-[var(--grud-error)] ml-1">*</span>}
                </td>
                <td className="px-4 py-2">
                  <code className="text-xs bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] px-2 py-1 rounded">
                    {param.schema?.type || param.type || 'string'}
                  </code>
                </td>
                <td className="px-4 py-2">
                  <span className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-1 rounded">
                    {param.in}
                  </span>
                </td>
                <td className="px-4 py-2 text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)]">{param.description || '-'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  };

  const renderJsonSchema = (schema: JsonSchema): JSX.Element | null => {
    if (!schema) return null;

    if (schema.type === 'object' && schema.properties) {
      return (
        <div className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] rounded p-4 space-y-2">
          {Object.entries(schema.properties).map(([propName, propSchema]) => (
            <div key={propName} className="font-mono text-sm">
              <div className="flex items-start gap-2">
                <span className="text-blue-600 dark:text-blue-400">"{propName}"</span>
                <span className="text-[var(--grud-text-secondary)]">:</span>
                <span className="text-purple-600 dark:text-purple-400">
                  {propSchema.type || 'any'}
                  {schema.required?.includes(propName) && <span className="text-[var(--grud-error)] ml-1">*</span>}
                </span>
              </div>
              {propSchema.description && (
                <div className="text-[var(--grud-text-secondary)] text-xs ml-4 mt-1">// {propSchema.description}</div>
              )}
            </div>
          ))}
        </div>
      );
    }

    return (
      <div className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] rounded p-4">
        <code className="text-sm">{schema.type || 'any'}</code>
        {schema.description && <span className="text-[var(--grud-text-secondary)] ml-2 text-sm">// {schema.description}</span>}
      </div>
    );
  };

  const executeRequest = async () => {
    setIsTestLoading(true);
    try {
      const serverBaseUrl = spec?.servers?.[0]?.url || baseUrl || '';
      let url = serverBaseUrl + path;

      // Replace path parameters
      Object.entries(testRequest.pathParams || {}).forEach(([key, value]) => {
        url = url.replace(`{${key}}`, encodeURIComponent(value as string));
      });

      // Add query parameters
      const queryParams = new URLSearchParams(testRequest.queryParams || {});
      if (queryParams.toString()) {
        url += '?' + queryParams.toString();
      }

      const response = await performApiTest(
        url,
        method,
        { 'Content-Type': 'application/json', ...testRequest.headers },
        testRequest.body
      );

      setTestResponse({
        status: response.status,
        statusText: response.statusText,
        headers: response.headers,
        data: response.data,
        url: response.url,
        error: response.error,
      });
    } catch (error) {
      setTestResponse({
        error: error instanceof Error ? error.message : 'Request failed',
      });
    } finally {
      setIsTestLoading(false);
    }
  };

  if (!operation) {
    // Show available operations for debugging
    const availableOps = spec?.paths ? Object.entries(spec.paths).flatMap(([path, pathItem]) =>
      Object.entries(pathItem)
        .filter(([method]) => ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'].includes(method.toLowerCase()))
        .map(([method, op]) => {
          const cleanPath = path.replace(/^\//, '').replace(/\//g, '_') || 'root';
          return {
            display: `${method.toUpperCase()} ${path}`,
            operationId: op.operationId || `${method.toUpperCase()}_${cleanPath}`,
          };
        })
    ) : [];

    return (
      <Card className="my-4 bg-white/80 dark:bg-[var(--grud-code-bg)]/80 backdrop-blur-sm border border-[color-mix(in_srgb,var(--grud-error)_30%,transparent)]/50 dark:border-red-900/50">
        <CardBody className="py-8">
          <div className="space-y-4">
            <p className="text-[var(--grud-error)] dark:text-[var(--grud-error)] font-semibold">
              ❌ Operation "{operationId}" not found in OpenAPI spec
            </p>
            {availableOps.length > 0 && (
              <div className="text-left">
                <p className="text-sm font-semibold text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)] mb-2">
                  Available operations:
                </p>
                <div className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] rounded p-3 max-h-60 overflow-y-auto">
                  {availableOps.map((op, idx) => (
                    <div key={idx} className="text-xs font-mono mb-1 text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)]">
                      <span className="text-[var(--grud-success)] dark:text-[var(--grud-success)]">{op.display}</span>
                      <span className="text-[var(--grud-text-secondary)]"> → </span>
                      <code className="bg-gray-200 dark:bg-[var(--grud-code-bg)] px-1 rounded">id: {op.operationId}</code>
                    </div>
                  ))}
                </div>
                <p className="text-xs text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)] mt-2">
                  💡 Use one of these IDs in your operation-ref directive
                </p>
              </div>
            )}
          </div>
        </CardBody>
      </Card>
    );
  }

  return (
    <Card className="my-4 bg-white/80 dark:bg-[var(--grud-code-bg)]/80 backdrop-blur-sm border border-[var(--grud-border-color)]/20 dark:border-[var(--grud-code-border)]/20 shadow-lg hover:shadow-xl transition-all duration-300">
      <CardBody>
        {/* Operation Header */}
        <div className="mb-4">
          <div className="flex items-center gap-3 mb-2">
            <Chip color={getMethodColor(method) as "default" | "primary" | "secondary" | "success" | "warning" | "danger"} size="md" variant="flat" className="font-semibold">
              {method}
            </Chip>
            <code className="text-sm bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] px-3 py-1 rounded font-mono">
              {path}
            </code>
          </div>
          <h3 className="text-xl font-semibold text-[var(--grud-text)] dark:text-[var(--grud-text)]">
            {operation.summary || `${method} ${path}`}
          </h3>
          {operation.description && (
            <p className="text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)] mt-2">{operation.description}</p>
          )}
        </div>

        <Divider className="my-4" />

        {/* Tabs */}
        <Tabs variant="underlined" className="w-full">
          <Tab key="overview" title="Overview">
            <div className="space-y-6 py-4">
              {/* Parameters */}
              {operation.parameters && operation.parameters.length > 0 && (
                <div>
                  <h4 className="text-lg font-semibold mb-3">Parameters</h4>
                  {renderParametersTable(operation.parameters)}
                </div>
              )}

              {/* Request Body */}
              {operation.requestBody && (
                <div>
                  <h4 className="text-lg font-semibold mb-3">Request Body</h4>
                  {operation.requestBody.description && (
                    <p className="text-sm text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)] mb-3">
                      {operation.requestBody.description}
                    </p>
                  )}
                  {operation.requestBody.content &&
                    Object.entries(operation.requestBody.content).map(([contentType, content]) => (
                      <div key={contentType} className="mb-4">
                        <div className="text-sm mb-2">
                          Content-Type: <code className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] px-2 py-1 rounded">{contentType}</code>
                        </div>
                        {content.schema && renderJsonSchema(content.schema)}
                      </div>
                    ))}
                </div>
              )}

              {/* Responses */}
              {operation.responses && (
                <div>
                  <h4 className="text-lg font-semibold mb-3">Responses</h4>
                  <div className="space-y-4">
                    {Object.entries(operation.responses).map(([status, response]) => (
                      <div key={status} className="border border-[var(--grud-border-color)] dark:border-[var(--grud-code-border)] rounded-lg p-4">
                        <div className="flex items-center gap-3 mb-2">
                          <Chip
                            size="sm"
                            color={
                              status.startsWith('2') ? 'success' : status.startsWith('4') ? 'warning' : 'danger'
                            }
                            variant="flat"
                          >
                            {status}
                          </Chip>
                          <span className="text-sm text-[var(--grud-text-secondary)] dark:text-[var(--grud-text-secondary)]">
                            {response.description || 'No description'}
                          </span>
                        </div>
                        {response.content &&
                          Object.entries(response.content).map(([contentType, content]) => (
                            <div key={contentType} className="mt-3">
                              <div className="text-sm mb-2">
                                Content-Type: <code className="bg-[var(--grud-surface-alt)] dark:bg-[var(--grud-code-bg)] px-2 py-1 rounded text-xs">{contentType}</code>
                              </div>
                              {content.schema && renderJsonSchema(content.schema)}
                            </div>
                          ))}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </Tab>

          <Tab key="try-it" title="Try It">
            <div className="py-4 space-y-6">
              {/* Request Form */}
              <div>
                <h4 className="text-lg font-semibold mb-4">Request</h4>

                {/* Path Parameters */}
                {(operation.parameters?.filter((p) => p.in === 'path').length || 0) > 0 && (
                  <div className="mb-4">
                    <h5 className="font-medium mb-2">Path Parameters</h5>
                    <div className="space-y-2">
                      {operation.parameters
                        ?.filter((p) => p.in === 'path')
                        .map((param) => (
                          <Input
                            key={param.name}
                            label={param.name}
                            placeholder={param.description}
                            isRequired={param.required}
                            onChange={(e) =>
                              setTestRequest((prev) => ({
                                ...prev,
                                pathParams: { ...prev.pathParams, [param.name]: e.target.value },
                              }))
                            }
                          />
                        ))}
                    </div>
                  </div>
                )}

                {/* Query Parameters */}
                {(operation.parameters?.filter((p) => p.in === 'query').length || 0) > 0 && (
                  <div className="mb-4">
                    <h5 className="font-medium mb-2">Query Parameters</h5>
                    <div className="space-y-2">
                      {operation.parameters
                        ?.filter((p) => p.in === 'query')
                        .map((param) => (
                          <Input
                            key={param.name}
                            label={param.name}
                            placeholder={param.description}
                            isRequired={param.required}
                            onChange={(e) =>
                              setTestRequest((prev) => ({
                                ...prev,
                                queryParams: { ...prev.queryParams, [param.name]: e.target.value },
                              }))
                            }
                          />
                        ))}
                    </div>
                  </div>
                )}

                {/* Request Body */}
                {['POST', 'PUT', 'PATCH'].includes(method) && (
                  <div className="mb-4">
                    <h5 className="font-medium mb-2">Request Body</h5>
                    <EnhancedCodeEditor
                      placeholder="Enter JSON request body"
                      value={testRequest.body || '{}'}
                      onChange={(value) => setTestRequest((prev) => ({ ...prev, body: value }))}
                      language="json"
                      height={200}
                      title="Request Body"
                    />
                  </div>
                )}

                <Button color="primary" size="lg" onPress={executeRequest} isLoading={isTestLoading} className="w-full">
                  Send Request
                </Button>
              </div>

              {/* Response Section */}
              {testResponse && (
                <div>
                  <h4 className="text-lg font-semibold mb-4">Response</h4>
                  {testResponse.error ? (
                    <div className="bg-[color-mix(in_srgb,var(--grud-error)_10%,transparent)] dark:bg-red-900/20 border border-[color-mix(in_srgb,var(--grud-error)_30%,transparent)] dark:border-red-800 rounded-lg p-4">
                      <h5 className="font-medium text-red-800 dark:text-red-200 mb-2">Error</h5>
                      <code className="text-sm text-[var(--grud-error)] dark:text-[var(--grud-error)]">{testResponse.error}</code>
                    </div>
                  ) : (
                    <>
                      <div className="mb-4">
                        <Chip color={(testResponse.status ?? 500) < 400 ? 'success' : 'danger'} variant="flat">
                          {testResponse.status} {testResponse.statusText}
                        </Chip>
                      </div>
                      <div>
                        <h5 className="font-medium mb-2">Response Body</h5>
                        <EnhancedCodeEditor
                          value={
                            typeof testResponse.data === 'object'
                              ? JSON.stringify(testResponse.data, null, 2)
                              : String(testResponse.data ?? '')
                          }
                          readOnly
                          language={typeof testResponse.data === 'object' ? 'json' : 'plaintext'}
                          height={250}
                          allowCopy
                          title="Response Body"
                        />
                      </div>
                    </>
                  )}
                </div>
              )}
            </div>
          </Tab>
        </Tabs>
      </CardBody>
    </Card>
  );
};

export default EmbeddedOperationViewer;
